README.md: Direct link to SC 3.1.5
xi/simple-alternative pull request #1
Opened 2017-07-20 13:32 UTC by cstrobbe

2017-07-20 21:55 UTC, xi requested changes
Thanks for the contribution! I have just some stylistic remark.

2017-07-20 21:55 UTC, xi commented on README.md
> +Among other things, it can be used to conform with [Success Criterion 3.1.5 in WCAG 2.0][2]:
This should be wrapped to stay within 80 character per line.

2017-07-20 21:55 UTC, xi commented on README.md
> +[2]: https://www.w3.org/TR/2008/REC-WCAG20-20081211/#meaning-supplements
Is there any harm in linking to <https://www.w3.org/TR/WCAG20/#meaning-supplements>? I do not expect breaking changes there.

2017-07-21 09:04 UTC, cstrobbe commented on README.md
> +[2]: https://www.w3.org/TR/2008/REC-WCAG20-20081211/#meaning-supplements
Linking directly to https://www.w3.org/TR/WCAG20/#meaning-supplements should be fine. Any changes to the SC would end up in WCAG 2.1.

2017-07-21 11:28 UTC, xi commented
Thanks

2017-07-21 11:28 UTC, xi approved these changes

2017-07-21 11:28 UTC, merged